---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    base_image: debian:buster
    container_name: php_apache_build_container
    image_namespace: geerlingguy
    image_name: php-apache

    # Apache settings.
    apache_remove_default_vhost: yes

    # PHP settings.
    php_version: '7.3'
    php_packages_extra:
      - libapache2-mod-php7.3
    php_install_recommends: no

    # Handy utilities.
    handy_utilities:
      - curl
      - unzip
      - tar
      - sudo

  pre_tasks:
    - name: Make the latest version of the base image available locally.
      docker_image:
        name: '{{ base_image }}'
        source: pull
        force_source: true

    - name: Create the Docker container.
      docker_container:
        image: '{{ base_image }}'
        name: '{{ container_name }}'
        command: sleep infinity

    - name: Add the newly created container to the inventory.
      add_host:
        hostname: '{{ container_name }}'
        ansible_connection: docker

    - name: Ensure Python is installed.
      raw: >
        apt-get update &&
        apt-get install -y --no-install-recommends python
      delegate_to: '{{ container_name }}'

    - name: Gather facts inside the container.
      setup:
      delegate_to: '{{ container_name }}'

    - name: Install handy utilities.
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ handy_utilities }}"
      delegate_to: '{{ container_name }}'

  roles:
    - name: geerlingguy.apache
      delegate_to: '{{ container_name }}'

    - name: geerlingguy.php-versions
      delegate_to: '{{ container_name }}'

    - name: geerlingguy.php
      delegate_to: '{{ container_name }}'

    - name: geerlingguy.php-mysql
      delegate_to: '{{ container_name }}'

    - name: geerlingguy.composer
      delegate_to: '{{ container_name }}'

  post_tasks:
    - name: Clean up the container.
      shell: >
        apt-get remove --purge -y python &&
        rm -rf /var/lib/apt/lists/*
      delegate_to: '{{ container_name }}'

    - name: Commit the container.
      command: >
        docker commit
        -c 'CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]'
        {{ container_name }} {{ image_namespace }}/{{ image_name }}:{{ php_version }}

    - name: Remove the container.
      docker_container:
        name: '{{ container_name }}'
        state: absent
